### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by vporoshok** [digitalcraftsman/hugo-type-theme#11]
Hi! Thanks for this great theme! I've not found how to add visible tag to post. How can I add tags?

**Comment by digitalcraftsman** [comment]
Hello @vporoshok,

the tags were not displayed until now like in the original theme. While refactoring parts of the theme I made them visible. Just pull the latest changes.

Cheers,
Digtitalctaftsman

**Comment by vporoshok** [comment]
Thank you!
