### ISSUE TITLE
disqus doesn't show up

### ISSUE THREAD

**Issue by gonzaloserrano** [digitalcraftsman/hugo-type-theme#15]
Hey there,

First, i love your theme and i'm using it for bcneng.net, so a big thank you.

Second, I've just added the disqus config var `disqusShortname = "my-short-code"` in my `config.toml` but the disqus widget is not showing app in the post pages. Also i've looked for `disqusShortname` in the templates but haven't find anything interesting.

Any hints? Thanks!

**Comment by digitalcraftsman** [comment]
Hi @gonzaloserrano,

I'm not sure why the disqus template wasn't embedded for single pages. Nonetheless, I added the template at the expected place. Just pull the latest commits.

Happy hugo-ing,
Digitalcraftsman

**Comment by gonzaloserrano** [comment]
Awesome, thanks for the quick fix!
