### ISSUE TITLE
Removing Disqus from About/index.md page

### ISSUE THREAD

**Issue by omartan** [digitalcraftsman/hugo-type-theme#16]
Hi,

Is there any way to remove disqus from the about/index.md page? It feels out of place for an about page to have commenting system.

Also, is it a known occurrence that about/index.md won't preview properly while in a local environment? As in my local environment, I can't preview my about page but once loaded online, it previews just fine.

**Comment by wysie** [comment]
I'm pretty sure this issue is related to Hugo 0.18. Since all the pages are now treated the same, your About index.md page is being rendered like a post. The solution would probably be to create a partials/section.html file in the theme, and then remove the Disqus section...
