### ISSUE TITLE
Speakerdeck as Social icon

### ISSUE THREAD

**Issue by andygrunwald** [digitalcraftsman/hugo-type-theme#21]
It would be good to have https://speakerdeck.com/[PROFILE] as a social icon as well.
Sadly Speakerdeck is (not yet) part of font-aweseome.
But those tickets are already open:

* https://github.com/FortAwesome/Font-Awesome/issues/1688
* https://github.com/FortAwesome/Font-Awesome/issues/4206
* https://github.com/FortAwesome/Font-Awesome/issues/6568

**Comment by digitalcraftsman** [comment]
Hello @andygrunwald,

I didn't find any indicators that could help to estimate the date of the inclusion of the speakerdeck icon. Hence I'll leave this issue open as a feature request.

**Comment by andygrunwald** [comment]
That is fine. Thank you.

**Comment by andygrunwald** [comment]
Two years later it is there. I made an PR: https://github.com/digitalcraftsman/hugo-type-theme/pull/39

**Comment by digitalcraftsman** [comment]
Fixed in #39
