### ISSUE TITLE
Links in posts are not differentiable

### ISSUE THREAD

**Issue by meetmangukiya** [digitalcraftsman/hugo-type-theme#24]
Maybe use different text color for anchored texts, or underline it or whatever feels appropriate to make it differentiable and so user understands that given text is a link

**Comment by meetmangukiya** [comment]
Example : https://meetmangukiya.github.io/post/coala/ last line, the proposal word is a link...

**Comment by meetmangukiya** [comment]
Ok, so the problem was that the link was made in a heading. I changed to bold text and the link is highlighted. Close if it link highlighting in heading seems pointless to you ;)

**Comment by andygrunwald** [comment]
@digitalcraftsman This issue can be closed :)
