### ISSUE TITLE
'tags' not working as expected on exampleSite

### ISSUE THREAD

**Issue by rootkea** [digitalcraftsman/hugo-type-theme#37]
Hello!

1. I expected a list of tags at baseurl/tags but it just displays the posts.  
e.g. https://themes.gohugo.io//theme/type/tags

2. I expected a list of posts tagged with 'jekyll' at baseurl/tags/jekyll but it displays all the posts instead.  
e.g. https://themes.gohugo.io//theme/type/tags/jekyll

**Comment by MuraEnok** [comment]
Hello, I would also like to get this function to work with this theme.  I use this theme for my blog and I can not figure out how to make tags or categories work.  Any guidance to how to make this work would be appreciated.
