### ISSUE TITLE
Missing "/" for RSS and Tags

### ISSUE THREAD

**Issue by FrankieSanzica** [digitalcraftsman/hugo-type-theme#45]
Hello,

While enabling RSS using your Hugo theme I'm being directed to:

https://EXAMPLE.COMindex.xml/ instead of https://EXAMPLE.COM/index.xml/

I'm also noticing something similar with tags:

https://EXAMPLE.COMtags/TAG instead of https://EXAMPLE.COM/tags/TAG

Or am I just doing something wrong?

Regards,

Frankie Sanzica

**Comment by digitalcraftsman** [comment]
Hey Frankie,

you added the type theme with commit 04070c6. In the last 24 hours a few changes have been made which also updated the code for the link to RSS feed. Could you update to the latest commit and report back if the problems are still there?

**Comment by FrankieSanzica** [comment]
Hello,

Now I'm getting this when using "hugo server -D":

`Building sites … ERROR 2019/07/04 21:37:38 render of "page" failed: execute of template failed: template: _default/single.html:3:3: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "~/themes/hugo-type-theme/layouts/partials/head.html:32:17": execute of template failed: template: _internal/opengraph.html:32:17: executing "_internal/opengraph.html" at <index $siteSeries $name>: error calling index: index of untyped nil`

**Comment by digitalcraftsman** [comment]
In a recent commit we added support for Opengraph, a way to store metadata in a website. Template requires a taxonomy named `series`. The default taxonomies `categories` and `tags` have to be redefined as well.

To fix that please copy [this lines into you config file](https://github.com/digitalcraftsman/hugo-type-theme/blob/master/exampleSite/config.toml#L36-L41). I have to document this changes as part of a new release.

**Comment by FrankieSanzica** [comment]
Hello,

That got the site back working but didn't fix the initial issue.

However, I found a workaround by just making sure I added the "/" the "baseurl" variable in the config.toml.

Regards,

Frankie.

**Comment by digitalcraftsman** [comment]
Great to hear that it's working now. I see that you're using Hugo v0.54 to generate your website. The issue might be fixed with one of the newer releases. I'm running Hugo v0.55.6 and don't experienced the issues you described even if I try different versions of the baseurl.

Are there any other issues with this theme? You're website seems to run fine

**Comment by digitalcraftsman** [comment]
I'll close this issue due to inactivity. Feel free to reopen it if the bug is still present.
